version: '3'

services:
  redis:
    image: 'redis:latest'

  web:
    build: .
    depends_on:
      - redis
    command: gunicorn --bind 0.0.0.0:8000
      --access-logfile -
      --reload
      app:app
    volumes:
      - '.:/sunsetter'
    environment: 
      - DEVELOPMENT=true
      - REDIS_HOST=redis
    env_file:
      - development.env
    ports:
      - '8000:8000'
