version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - GIT_COMMIT_SHA1_BUILD
    volumes:
      - '.:/sunsetter'
    env_file:
      - development.env
    ports:
      - '8000:8000'
