version: '3'

services:
  web:
    build:
      context: .
      args:
        - GIT_COMMIT_SHA1_BUILD
    image: sunsetter:prod
    volumes:
      - '.:/sunsetter'
    environment: 
      - PORT=8000
    env_file:
      - development.env
    ports:
      - '8000:8000'
